import Lake
open Lake DSL

package «auto-blueprint-formalization» where
  -- This Lake project exists so Auto-Blueprint can run Lean as a real critic.
  -- Generated proof attempts are disposable files checked with `lake env lean`.

-- BEGIN MANAGED REQUIRES -- generated by `scripts/lean_libs.py apply`; do not edit by hand.
-- Revisions are RESOLVED, not authored: `lean_libs.py resolve` reads each
-- library's lean-toolchain history and picks the newest toolchain they all
-- support, then pins every library (and Mathlib) to a matching revision.
-- Never restore a floating ref such as `@ "master"` here: any lake invocation
-- would silently check out a newer Mathlib and invalidate the compiled tree,
-- and a Mathlib whose toolchain differs from `lean-toolchain` fails every
-- import with `incompatible header`.
require mathlib from git
  "https://github.com/leanprover-community/mathlib4.git" @ "81a5d257c8e410db227a6665ed08f64fea08e997"
require cslib from git
  "https://github.com/leanprover/cslib.git" @ "197a7be621263b84c67ca4f803f69205b36d06df"
require physlib from git
  "https://github.com/leanprover-community/physlib.git" @ "c217bdddb2da900732d8d864991b08bf1d91a2f4"
-- END MANAGED REQUIRES

@[default_target]
lean_lib AutoBlueprint where
